apiVersion: v1
kind: Pod
spec:
  containers:
  - command: ["/kubernetes-entrypoint.sh"]
    volumeMounts:
    - mountPath: /root/.livy-sessions
      name: livy-external-jars-share
  volumes:
  - name: livy-external-jars-share
    persistentVolumeClaim:
      claimName: livy-jars
