{{- if .Values.Livy.ServiceAccount.Create }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.Livy.Global.ImagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.Livy.Global.ImagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ include "livy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
{{- end }}
{{- if .Values.Livy.SparkServiceAccount.Create }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.Livy.Global.ImagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.Livy.Global.ImagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ include "livy.fullname" . }}-spark
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "livy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
